config/routes.rb
Skrimply::Application.routes.draw do
  devise_for :users

  resources :releases do
    resources :tracks, :only => [:create, :new]
  end

  resources :tracks do
    resources :definitions, :only => [:index]
  end

  resources :definitions, :only => [:create]
  resources :artists
  resources :genres
  resources :users, :only => [:index, :show]

  get '/about', to: 'static_pages#about'

  root to: 'static_pages#home'
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  duration   :string(255)
#  lyrics     :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Track < ActiveRecord::Base
  attr_accessor :set_owning_artists, :set_featuring_artists

  belongs_to :submitting_user, :class_name => "User", :foreign_key => "user_id"

  has_many :definitions
  has_many :appearances, inverse_of: :track
  has_many :artists, through: :appearances
  has_many :genre_tracks
  has_many :genres, through: :genre_tracks
  has_many :cuts, inverse_of: :track
  has_many :releases, through: :cuts
  has_one :youtube_video

  # accepts_nested_attributes_for :release_tracks,
  #                               :reject_if => :all_blank

  # accepts_nested_attributes_for :artist_tracks

  validates :name, :presence => true
  validates :lyrics, :presence => true

  after_save :set_appearing_artists

  def owning_artists
    artists.merge(Appearance.as_owner)
  end

  def owning_artist
    owning_artists.first
  end

  def featuring_artists
    artists.merge(Appearance.as_featured)
  end

  def youtubeable_title
    "#{owning_artist.name} - #{name}"
  end

  private  
    def set_appearing_artists
      # Clear out all associations
      self.appearances.destroy_all

      if !set_owning_artists.nil? 
        set_owning_artists.each do |artist_id|
          self.appearances.as_owner.create!(artist: Artist.find(artist_id)) unless artist_id.blank?
        end
      end

      if !set_featuring_artists.nil?
        set_featuring_artists_without_duplicates = set_featuring_artists - set_owning_artists
        set_featuring_artists_without_duplicates.each do |artist_id|
          self.appearances.as_featured.create!(artist: Artist.find(artist_id)) unless artist_id.blank?
        end
      end
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:edit, :update, :destroy]

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id], include: [ :definitions, :genres, :youtube_video ])
  end

  def new
    @track = Track.new
    @track.cuts.build(release_id: params[:release_id])
  end

  def edit
    @track.cuts.build if @track.cuts.empty?
  end

  def create
    @track = Track.new(track_params)
    @track.submitting_user = current_user

    if @track.save
      redirect_to @track, notice: 'Track created.'
    else
      render action: "new"
    end
  end

  def update
    if @track.update(track_params)
      redirect_to @track, notice: 'Track updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @track.destroy
    redirect_to tracks_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:duration, :lyrics, :name, genre_ids: [], set_owning_artists: [], set_featuring_artists: [])
    end
end

app/views/tracks/_definition.html.erb
<div id="definition-<%= definition.id %>">
  <%= link_to definition.submitting_user.display_name, definition.submitting_user %> said...
  <%= simple_format definition.text %>
</div>

app/views/tracks/_definition_modal.html.erb
<%= simple_form_for(Definition.new) do |f| %>
  <div id="definitionModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="definitionModal" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h2>Define Lyrics <small>write a bad romance</small></h2>
    </div>
    <div class="modal-body">
      <div class="left">
        <h3>These lyrics</h3>
        <pre id="selectedSongLyrics"></pre>
      </div>
      <div class="right">
        <h3>...mean</h3>
        <% if user_signed_in? %>
          <%= f.text_area    :text, :placeholder => "Your description here" %>
          <%= f.hidden_field :track_id, :value =>  @track.id %>
          <%= f.hidden_field :range_start %>
          <%= f.hidden_field :range_end %>
        <% else %>
          You must <a href="#loginModal" role="button" data-toggle="modal">be signed in</a>
          or
          <a href="#registerModal" role="button" data-toggle="modal">create an account</a> to leave your mark!
        <% end %>
      </div>
    </div>
    <div class="modal-footer">
      <% if user_signed_in? %>
        <button class="btn btn-primary">Submit!</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true" id="cancelDefineSongModal">Cancel</button>
      <% else %>
        <a href="#loginModal" role="button" data-toggle="modal" class="btn btn-primary">Sign In!</a>
        <a href="#registerModal" role="button" data-toggle="modal" class="btn btn-success">Sign Up</a>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tracks/_form.html.erb
<%= simple_form_for(@track) do |f|  %>

  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>

  <legend>Track Info</legend>
  <%= f.input :name %>

  <%= f.input :duration %>

  <%= f.association :genres %>

  <%= f.input :lyrics %>
  
  <p>  
    <%= f.label :set_owning_artists %>
    <br />
    <%= f.select :set_owning_artists, Artist.all.map { |x| [x.name, x.id] }, { selected: @track.owning_artists.map(&:id) }, { multiple: true } %>
  </p>

  <p>
    <%= f.label :set_featuring_artists %>
    <br />
    <%= f.select :set_featuring_artists, Artist.all.map { |x| [x.name, x.id] }, { selected: @track.featuring_artists.map(&:id) }, { multiple: true } %>
  </p>

  <legend>Release Info (optional)</legend>
  <= f.simple_fields_for :release_tracks do |rt| %>
    <= rt.association :release %>
    <= rt.input :position %>
  < end %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>

<% end %>

app/views/tracks/_javascript_vars.html.erb
<script>
  Skrimply.track_definitions_url = "<%= track_definitions_path(@track, :json) %>";
</script>

app/views/tracks/edit.html.erb
<div class="page-header">
  <h1>Editing Track</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<div class="page-header">
  <h1>All Tracks</h1>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Featuring</th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
    <td><%= link_to track.name, track %></td>
    <td><%= link_to track.owning_artist.name, track.owning_artist %></td>
    <td>
      <%= track.featuring_artists.collect { |artist| link_to artist.name, artist }.join(", ").html_safe %>
    </td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<div class="page-header">
  <h1>New Track</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<div class="page-header">
  <h1><%= @track.name %>
    <small>by <%= link_to @track.owning_artist.name.titleize, artist_path(@track.owning_artist) %>
    <% unless @track.featuring_artists.empty? %>
      featuring <%= @track.featuring_artists.map(&:name).to_sentence %>
    <% end %>
    </small></h1>
</div>

<div class="row">
  <div class="span5">
    <h1>Lyrics</h1>
    <div id="lyrics">
      <%= simple_format @track.lyrics %>
    </div>
  </div>

  <div class="span4">
    <h2>Definitions</h2>
    <% if @track.definitions.empty? %>
      <p>None... yet.</p>
      <%= image_tag "rage-horror.png" %>
    <% else %>
      <%= render :partial => "definition", :collection => @track.definitions %>
    <% end %>
  </div>

  <div class="span3">
    <div class="well well-large">
      <h4>Track Information</h4>
      <hr>

      <h5>Artist</h5>
      <%= link_to @track.owning_artist.name.titleize, artist_path(@track.owning_artist) %>
      <hr>

      <% unless @track.featuring_artists.empty? %>
        <h5>Featured Artists</h5>
        <%= @track.featuring_artists.map do |artist|
          link_to artist.name, artist
          end.to_sentence.html_safe %>
        <hr>
      <% end %>

      <% unless @track.genres.empty? %>
        <h5>Genres</h5>
        <ul>
          <% @track.genres.each do |genre| %>
            <li>
              <%= link_to genre.name.titleize, genre_path(genre) %>
            </li>
          <% end %>
        </ul>
        <hr>
      <% end %>

      <% unless @track.cuts.empty? %>
        <h5>On Releases</h5>
        <ul>
          <% @track.cuts.each do |cut| %>
            <li>
              <%= link_to cut.release.name.titleize, release_path(cut.release) %> as track #<%= cut.position %>
            </li>
          <% end %>
        </ul>
        <hr>
      <% end %>

      <% unless @track.duration.empty? %>
        <h5>Duration</h5>
        <%= @track.duration %>
        <hr>
      <% end %>

      <h5>Submitter</h5>
      <%= link_to @track.submitting_user.display_name, @track.submitting_user %>

    </div>

  </div>
</div>

<hr>

<div class="row">
  <% unless @track.youtube_video.nil? %>
    <h2>Watch</h2>
    <%= raw @track.youtube_video.embed_html %>
  <% end %>
</div>



<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>

<%= render 'tracks/definition_modal' %>
<%= render 'tracks/javascript_vars' %>