config/routes.rb
Skrimply::Application.routes.draw do
  devise_for :users

  resources :releases do
    resources :tracks, :only => [:create, :new]
  end

  resources :tracks do
    resources :definitions, :only => [:index]
  end

  resources :definitions, :only => [:create]
  resources :artists
  resources :genres
  resources :users, :only => [:index, :show]

  get '/about', to: 'static_pages#about'

  root to: 'static_pages#home'
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Artist < ActiveRecord::Base
  belongs_to :submitting_user, class_name: 'User', foreign_key: 'user_id'

  has_many :appearances, inverse_of: :artist
  has_many :releases, through: :appearances
  has_many :tracks, through: :appearances
  has_many :artist_genres
  has_many :genres, through: :artist_genres

  # attr_accessible :name, :genre_ids

  validates :name, :presence => true
  validates :name, :uniqueness => true

  def tracks_owned
    tracks.merge(Appearance.as_owner)
  end

  def tracks_featured_on
    tracks.merge(Appearance.as_featured)
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :create]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.submitting_user = current_user

    if @artist.save
      redirect_to @artist, notice: 'Artist created.'
    else
      render action: "new"
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist, notice: 'Artist updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_url
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :genre_ids)
    end
end

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f|  %>

  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>

  <%= f.input :name %>

  <%= f.association :genres %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>

<% end %>

app/views/artists/edit.html.erb
<div class="page-header">
  <h1>Editing Artist</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<div class="page-header">
  <h1>All Artists</h1>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Added</th>
    <th></th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= link_to artist.name, artist %></td>
    <td><%= time_ago_in_words artist.created_at %> ago</td>
    <td>
      <% if current_user == artist.submitting_user %>
        <%= link_to 'Edit', edit_artist_path(artist) %> |
        <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in? %>
  <%= link_to 'New Artist', new_artist_path %>
<% end %>

app/views/artists/new.html.erb
<div class="page-header">
  <h1>New Artist</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<div class="page-header">
  <h1><%= @artist.name %> <small>artist</small></h1>
</div>

<h2>Submitted By</h2>
<h4><%= @artist.submitting_user.display_name %></h4>

<h2>Releases</h2>
<ul>
  <% @artist.releases.each do |release| %>
    <li>
      <span class="label label-info"><%= release.release_kind.name.titleize %></span>
      <%= link_to release.name.titleize, release_path(release) %>
    </li>
  <% end %>
</ul>
<% if  user_signed_in? %>
  <%= link_to "Add", new_release_path %>
<% end %>


<h2>All Tracks</h2>
<ul>
  <% @artist.tracks.each do |track| %>
    <li>
      <%= link_to track.name.titleize, track_path(track) %>
    </li>
  <% end %>
</ul>
<% if  user_signed_in? %>
  <%= link_to "Add", new_track_path %>
<% end %>


<h3>Authored</h3>
<ul>
  <% @artist.tracks_owned.each do |track| %>
    <li>
      <%= link_to track.name.titleize, track_path(track) %>
    </li>
  <% end %>
</ul>

<h3>Featured On</h3>
<ul>
  <% @artist.tracks_featured_on.each do |track| %>
    <li>
      <%= link_to track.name.titleize, track_path(track) %> by <%= link_to track.owning_artist.name.titleize, artist_path(track.owning_artist) %>
    </li>
  <% end %>
</ul>

<h2>Genres</h2>
<ul>
  <% @artist.genres.each do |genre| %>
    <li>
      <%= link_to genre.name.titleize, genre_path(genre) %>
    </li>
  <% end %>
</ul>

<% if current_user == @artist.submitting_user %>
  <%= link_to 'Edit', edit_artist_path(@artist) %> |
<% end %>

<%= link_to 'Back', artists_path %>